import Layout from '@/components/Layout'
import Head from 'next/head'
import profilepic from '../../public/images/profile/developer-pic-1.png'
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className="flex items-center text-dark  w-full min-h-screen ">
        <Layout className={"!pt-0"}>
          <div className='md:flex w-full items-center justify-between  '>
            <div className='flex-1'>
              <Image src={profilepic} alt="user" className="w-full h-auto" />
            </div>
            <div className='flex-1 flex flex-col self-center '>
              <AnimatedText className='!text-3xl md:!text-4xl lg:!text-6xl md:text-left'
                text={"Turning Vision into reality with code and design"}
              />
              <p
                className='my-4 text-base font-medium '
              >
                As a skilled full-stac developer , I am dedicated to turning ideas inot innovative web application Explore my
                latest projects abd articles showcasting my experties in React.js ,nodejs ,web development
              </p>
              <div>
                <Link href="../../public/dummy.pdf" download={true}>
                  Resume
                </Link>
                <Link href="mailto:bateemma14@gmail.com" >
                  Contact Me
                </Link>
              </div>

            </div>
          </div>

        </Layout>
      </main>
    </>
  )
}
